name: SambaLolo Production
favicon: null
layout_spectrum: 0.8717576891649514
typography_spectrum: 0.564045931212604
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.9667667283210903
  lightness: 0.8789183346088976
  saturation: 0.5234620480332524
  rhythmicContrast: 0.29732408351264894
purpose: []
