name: SambaLolo Production
favicon: null
layout_spectrum: 0.92742
typography_spectrum: 0.47128
title: "Messenger's Music Labs"
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#cba580'
    - '#1b120b'
    - '#84796f'
    - '#fc604a'
  brandStrength: 0.375
  lightness: 0
  saturation: 0.75
  rhythmicContrast: 0.75
purpose: []
